eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: false
  #自我保护、开发环境中关闭
  server:
    enable-self-preservation: false
spring:
  application:
    name: eurekaServer
server:
  port: dev
